---
title: "STA 198 Project"
author: ""
format: pdf
---


```{r}
library(tidyverse)
library(ggplot2)
data <- read_csv("DonorHyperglycemia.csv")
```

###Exploratory Analysis

```{r}
  ggplot(data = data, aes(x = glutwa)) +
      geom_histogram()  +
  labs(
    title = "Distribution of Time Weighted Average of Glucose in Liver Graft (GLUTWA) of Donors",
    x = "Time Weighted Average of Glucose in Liver Graft",
    y = "Count"
  )

```

```{r}
  ggplot(data = data, aes(x = glurange)) +
      geom_histogram()  +
  labs(
    title = "Distribution of Range of Glucose in Liver Graft of Donors",
    x = "Range of Glucose in Liver Graft",
    y = "Count"
  )

```

```{r}
  ggplot(data = data, aes(x = glusd)) +
      geom_histogram()  +
  labs(
    title = "Distribution of Standard Deviations of Glucose in Liver Graft of Donors",
    x = "Standard Deviations of Glucose in Liver Graft",
    y = "Count"
  )

```


```{r}
data <- data |> 
  mutate(delayed_fn = factor(delayed_fn, labels = c("No Graft Dysfunction", "Graft Dysfunction")))
boxplot(glutwa ~ delayed_fn, data = data,
         main = "TWA of glucose obersrvations in liver graft vs delayed liver function",
         ylab = "Time weighted average of glucose obersrvations in liver graft")

```


```{r}
ggplot(data, aes(x = glutwa, fill = delayed_fn)) +
  geom_histogram(alpha = 0.7, position = "identity", bins = 30) +
  labs(
    title = "Distribution of TWA Glucose by Graft Dysfunction Status",
    x = "TWA glucose (mg/dL)",
    y = "Count",
    fill = "Delayed liver graft function"
  ) +
  theme_bw() +
  theme(plot.title = element_text(size = 14, face = "bold"))

```


```{r}
ggplot(data, aes(x = factor(delayed_fn))) +
  geom_bar(fill = "blue") +
  scale_x_discrete(labels = c("No Graft Dysfunction", "Delayed Graft Dysfunction")) +
  labs(title = "Graft Dysfunction Rate",
       x = "Outcome",
       y = "Count")
```
